### ISSUE TITLE
Currently used branch isn't named master

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/RmlUi#4]
Currently used branch isn't named `master`. It means we can't just checkout `master` in the submodule and then commit the submodule.

It happened to me today where I committed a now old and incompatible submodule using my script to sync our submodules from time to time:

https://github.com/Unvanquished/Unvanquished/commit/d31af322acd2417b6205ec0a97b6b46c7ae03f24

I had to revert it by hand:

https://github.com/Unvanquished/Unvanquished/commit/2c37599a4ca21259d3b4815283d7fca335acc16d

The branch we currently use is currently named `upstream` and is a recent snapshot of upstream's master plus this specific commit we need that is not upstreamed: https://github.com/Unvanquished/RmlUi/commit/cf67dbd7285049eee891af3f7c2443ced60be32e

**Comment by illwieckz** [comment]
I suggest to rename our current `master` to something like `legacy/early-port` or `legacy/unvanquished-0.53.1` or something like that and rename `upstream` branch to `master`.

If one day it happens we can follow upstream master without any custom patch we would be able to rename our then current `master` to `legacy/custom-nacl` or something like that and just make `master` an unmodified copy of upstream master.

**Comment by illwieckz** [comment]
Requesting comments from @slipher and @DolceTriade.

**Comment by DolceTriade** [comment]
Oops. That was my sloppiness. We should rename upstream to master for sure.

**Comment by illwieckz** [comment]
So we now have `master` which is the current branch we commit as Unvanquished submodule, it was renamed from `upstream`:

- https://github.com/Unvanquished/RmlUi/tree/master

And we have `legacy/early-port` that contains the branch that was previously named `master` and was used for Unvanquished 0.53.0 and 0.53.1, the commits for tags `unvanquished/0.53.0` and `unvanquished/0.53.1` are stored in this branch:

- https://github.com/Unvanquished/RmlUi/tree/legacy/early-port
